config/routes.rb
Rails.application.routes.draw do
  resources :service_configs

  get 'welcome/index'

  root "welcome#index"
end

app/models/service_config.rb
class ServiceConfig < ActiveRecord::Base

  validates :name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validate :atleast_one_is_checked

  def atleast_one_is_checked
    errors.add(:base, "Gotta have at least one service") unless website_needed || social_needed || video_needed || appdev_needed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/service_configs_controller.rb
class ServiceConfigsController < ApplicationController
  before_action :set_service_config, only: [:show, :edit, :update, :destroy]

  # GET /service_configs
  # GET /service_configs.json
  def index
    @service_configs = ServiceConfig.all
  end

  # GET /service_configs/1
  # GET /service_configs/1.json
  def show
  end

  # GET /service_configs/new
  def new
    @service_config = ServiceConfig.new
  end

  # GET /service_configs/1/edit
  def edit
  end

  # POST /service_configs
  # POST /service_configs.json
  def create
    @service_config = ServiceConfig.new(service_config_params)

    respond_to do |format|
      if @service_config.save
        format.html { redirect_to @service_config, notice: 'Service config was successfully created.' }
        format.json { render :show, status: :created, location: @service_config }
      else
        format.html { render :new }
        format.json { render json: @service_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_configs/1
  # PATCH/PUT /service_configs/1.json
  def update
    respond_to do |format|
      if @service_config.update(service_config_params)
        format.html { redirect_to @service_config, notice: 'Service config was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_config }
      else
        format.html { render :edit }
        format.json { render json: @service_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_configs/1
  # DELETE /service_configs/1.json
  def destroy
    @service_config.destroy
    respond_to do |format|
      format.html { redirect_to service_configs_url, notice: 'Service config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_config
      @service_config = ServiceConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_config_params
      params.require(:service_config).permit(:name, :phone, :email, :website_needed, :social_needed, :video_needed, :appdev_needed, :desired_contract_length)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @service_config = ServiceConfig.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_configs_helper.rb
module ServiceConfigsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThirtyNinth</title>

  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <style type="text/css">
    div.row.well a {
      color: white;
    }
  </style>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <%= csrf_meta_tags %>
<!-- 
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/knockout/3.1.0/knockout-min.js"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/knockout-bootstrap/0.2.1/knockout-bootstrap.js"></script>
   -->
</head>
<body>

<div class="row well">
  <%= link_to "Home", root_path %> | 
  <%= link_to "Service Configs", service_configs_path %>
</div>

  <div class="container">
    <div class="row">
      <h1>Thirty Ninth!!!</h1>
    </div>

    <div class="row" style="margin: 1em 0;">
      <hr>
    </div>

    <div class="row">
      <%= yield %>
    </div>

    <div class="row" style="margin: 1em 0;">
      <hr>
    </div>

    <footer style="margin-top: 2em;">
      <p>Footer info</p>
    </footer>
  </div>

</body>
</html>

app/views/service_configs/_form.html.erb
<%= form_for(@service_config) do |f| %>
  <% if @service_config.errors.any? %>
    <div class="row">
      <div id="error_explanation" class="alert alert-danger col-md-6">
        <% @service_config.errors.full_messages.each do |message| %>
          <h4><%= message %></h4>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name %><br>
      <div class='input-group'>
        <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
        <%= f.text_field :name, required: true, placeholder: "What's Your Name?", class: "form-control input-lg" %>
      </div>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :phone %>
      <div class='input-group'>
        <span class="input-group-addon"><span class="glyphicon glyphicon-earphone"></span></span>
        <%= f.text_field :phone, class: "form-control input-lg", required: true, placeholder: "What's Your Phone Number?" %>
      </div>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :email %><br>
      <div class='input-group'>
        <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
        <%= f.text_field :email, class: "form-control input-lg", required: true, placeholder: "What's Your Email?" %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="form-group col-md-3">
      <%= f.label :website_needed %>
      <%= f.check_box :website_needed %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :social_needed %>
      <%= f.check_box :social_needed %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :video_needed %>
      <%= f.check_box :video_needed %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :appdev_needed %>
      <%= f.check_box :appdev_needed %>
    </div>
  </div>


  <div class="row">
    <div class="form-group col-md-12">
      <%= f.label :desired_contract_length, "Desired contract length:" %>
      <span id="contract_months">12 months</span>
      <br>
      <%= f.range_field :desired_contract_length, in: 6..24, step: 1 %>
    </div>
  </div>

  <div class="row alert alert-success">
    <div class="form-group col-md-7">
      <h2>Base Subscription:
        <span id="base_subscription_cost"></span>
      </h2>
    </div>
  </div>

  <div class="form-group col-md-12 text-center">
    <%= f.submit "Submit Quote", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>


<script type="text/javascript">
  WEBSITE_COST = 7500;
  SOCIAL_COST  = 2500;
  VIDEO_COST   = 2500;
  APPDEV_COST  = 5000;
  $("input#service_config_desired_contract_length").val(12);
  calculate_monthly_cost();

  function total_service_cost() {
    total_cost = 0;

    if($('input#service_config_website_needed').is( ":checked" )) {
      total_cost += WEBSITE_COST;
    }
    if ($('input#service_config_social_needed').is( ":checked" )) {
      total_cost += SOCIAL_COST;
    }
    if ($('input#service_config_video_needed').is( ":checked" )) {
      total_cost += VIDEO_COST;
    }
    if ($('input#service_config_appdev_needed').is( ":checked" )) {
      total_cost += APPDEV_COST;
    }

    return total_cost;
  }

  function calculate_monthly_cost() {
    val = $("input#service_config_desired_contract_length").val();
    base_cost = total_service_cost();
    console.log(base_cost);
    subscription_price = Math.round((base_cost / val) * 100) / 100;
    
    $('#contract_months').text(val + " months");
    $('#base_subscription_cost').text("$" + (subscription_price) + "/mo");
  }

  $("input#service_config_desired_contract_length").change(function() {
    calculate_monthly_cost();
  });

  $("input[type='checkbox']").change(function() {
    calculate_monthly_cost();
  });


</script>

app/views/service_configs/edit.html.erb
<h1>Editing service_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_config %> |
<%= link_to 'Back', service_configs_path %>

app/views/service_configs/index.html.erb
<div class="col-lg-12">
  <div class="panel panel-default" id="headings">
    <div class="panel-heading">Service Configrations</div>
    <div class="panel-body">
      <h1 class="page-header">All of em</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Website needed</th>
            <th>Social needed</th>
            <th>Video needed</th>
            <th>Appdev needed</th>
            <th>Desired contract length</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @service_configs.each do |service_config| %>
            <tr>
              <td><%= service_config.name %></td>
              <td><%= service_config.phone %></td>
              <td><%= service_config.email %></td>
              <td><%= service_config.website_needed %></td>
              <td><%= service_config.social_needed %></td>
              <td><%= service_config.video_needed %></td>
              <td><%= service_config.appdev_needed %></td>
              <td><%= service_config.desired_contract_length %></td>
              <td><%= link_to 'Show', service_config %></td>
              <td><%= link_to 'Edit', edit_service_config_path(service_config) %></td>
              <td><%= link_to 'Destroy', service_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Service config', new_service_config_path %>

    </div>
  </div>
</div>

app/views/service_configs/new.html.erb
<div class="col-lg-12">
  <div class="panel panel-default" id="headings">
    <div class="panel-heading">Service Configrations</div>
    <div class="panel-body">

      <h1>New service_config</h1>

      <%= render 'form' %>

      <%= link_to 'Back', service_configs_path %>
    </div>
  </div>
</div>

app/views/service_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_config.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @service_config.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @service_config.email %>
</p>

<p>
  <strong>Website needed:</strong>
  <%= @service_config.website_needed %>
</p>

<p>
  <strong>Social needed:</strong>
  <%= @service_config.social_needed %>
</p>

<p>
  <strong>Video needed:</strong>
  <%= @service_config.video_needed %>
</p>

<p>
  <strong>Appdev needed:</strong>
  <%= @service_config.appdev_needed %>
</p>

<p>
  <strong>Desired contract length:</strong>
  <%= @service_config.desired_contract_length %>
</p>

<%= link_to 'Edit', edit_service_config_path(@service_config) %> |
<%= link_to 'Back', service_configs_path %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6">
    <div class="panel panel-default fade" id="headings">
      <div class="panel-heading">Headings with the .fade CSS class attached.</div>
      <div class="panel-body">
      <h1 class="page-header">Page Header <small>With Small Text</small></h1>
      <h1>This is an h1 heading</h1>
      <h2>This is an h2 heading</h2>
      <h3>This is an h3 heading</h3>
      <h4>This is an h4 heading</h4>
      <h5>This is an h5 heading</h5>
      <h6>This is an h6 heading</h6>
      </div>
    </div>
  </div>

  <div class="hidden-sm col-xs-4 col-md-6">
    <div class="panel panel-default" id="headings">
      <div class="panel-heading">Big form with lots of shit</div>
      <div class="panel-body">
        <h1 class="page-header">Page Header <small>With Small Text</small></h1>
        <p>Form data here</p>
      </div>
    </div>
  </div>
</div>

<div class="row" style="margin: 1em 0;">
  <hr>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render 'service_configs/form' %>
  </div>
</div>